import { SAFETY_COPY } from '@/constants/app';
import type { ContentPackManifest } from '@/types/content';

function kiwixSha256Url(sourceUrl: string) {
  return `${sourceUrl}.sha256`;
}

export const STARTER_PACKS: ContentPackManifest[] = [
  {
    id: 'hesperian-first-aid',
    title: 'Hesperian First Aid',
    description: 'Field-focused emergency care chapter from New Where There Is No Doctor.',
    category: 'Medical',
    format: 'pdf',
    estimatedSize: 'PDF chapter',
    sourceUrl: 'https://hesperian.org/wp-content/uploads/pdf/en_nwtnd_2011/en_nwtnd_2014_03g.pdf',
    sourceLabel: 'Hesperian Health Guides',
    fileName: 'hesperian-first-aid.pdf',
    installed: false,
    disclaimer: SAFETY_COPY.medical,
  },
  {
    id: 'us-army-survival-fm-21-76',
    title: 'US Army Survival Manual',
    description:
      'FM 21-76 survival reference covering shelter, water, fire, navigation, and signaling.',
    category: 'Survival',
    format: 'pdf',
    estimatedSize: '2.9 MB',
    sourceUrl:
      'https://ia601604.us.archive.org/28/items/Fm21-76SurvivalManual/FM21-76_SurvivalManual.pdf',
    sourceLabel: 'Internet Archive',
    fileName: 'fm-21-76-survival-manual.pdf',
    installed: false,
  },
  {
    id: 'usda-special-forest-products-harvest',
    title: 'Wild Plant Harvest Safety',
    description:
      'USDA Forest Service guidance for sustainable wild-plant gathering and harvest restraint.',
    category: 'Survival',
    format: 'pdf',
    estimatedSize: '58 pages',
    sourceUrl: 'https://research.fs.usda.gov/download/treesearch/45826.pdf',
    sourceLabel: 'USDA Forest Service',
    fileName: 'usda-special-forest-products-harvest.pdf',
    installed: false,
  },
  {
    id: 'where-there-is-no-doctor-first-aid',
    title: 'Where There Is No Doctor: First Aid',
    description: 'Classic Hesperian first-aid chapter for low-resource primary care situations.',
    category: 'Medical',
    format: 'pdf',
    estimatedSize: 'PDF chapter',
    sourceUrl: 'https://hesperian.org/wp-content/uploads/pdf/en_wtnd_2025/en_wtnd_2025_10.pdf',
    sourceLabel: 'Hesperian Health Guides',
    fileName: 'where-there-is-no-doctor-first-aid.pdf',
    installed: false,
    disclaimer: SAFETY_COPY.medical,
  },
  {
    id: 'wikipedia-simple-en-nopic',
    title: 'Simple English Wikipedia',
    description:
      'Complete Simple English Wikipedia, no images. Best first Wikipedia archive for phones.',
    category: 'Wiki',
    format: 'zim',
    estimatedSize: '937 MB',
    sizeBytes: 937 * 1024 * 1024,
    sourceUrl: 'https://download.kiwix.org/zim/wikipedia/wikipedia_en_simple_all_nopic_2026-05.zim',
    checksumSha256Url: kiwixSha256Url(
      'https://download.kiwix.org/zim/wikipedia/wikipedia_en_simple_all_nopic_2026-05.zim'
    ),
    sourceLabel: 'Kiwix ZIM archive',
    fileName: 'wikipedia_en_simple_all_nopic_2026-05.zim',
    installed: false,
  },
  {
    id: 'wikipedia-simple-en-mini',
    title: 'Simple English Wikipedia Mini',
    description: 'Introductory article extracts only. Smaller archive for low-storage devices.',
    category: 'Wiki',
    format: 'zim',
    estimatedSize: '447 MB',
    sizeBytes: 447 * 1024 * 1024,
    sourceUrl: 'https://download.kiwix.org/zim/wikipedia/wikipedia_en_simple_all_mini_2026-05.zim',
    checksumSha256Url: kiwixSha256Url(
      'https://download.kiwix.org/zim/wikipedia/wikipedia_en_simple_all_mini_2026-05.zim'
    ),
    sourceLabel: 'Kiwix ZIM archive',
    fileName: 'wikipedia_en_simple_all_mini_2026-05.zim',
    installed: false,
  },
  {
    id: 'medical-wikipedia-en-nopic',
    title: 'Medical Wikipedia',
    description:
      'English medical Wikipedia collection without images for offline health reference.',
    category: 'Medical',
    format: 'zim',
    estimatedSize: '822 MB',
    sizeBytes: 822 * 1024 * 1024,
    sourceUrl: 'https://download.kiwix.org/zim/wikipedia/wikipedia_en_medicine_nopic_2026-04.zim',
    checksumSha256Url: kiwixSha256Url(
      'https://download.kiwix.org/zim/wikipedia/wikipedia_en_medicine_nopic_2026-04.zim'
    ),
    sourceLabel: 'Kiwix ZIM archive',
    fileName: 'wikipedia_en_medicine_nopic_2026-04.zim',
    installed: false,
    disclaimer: SAFETY_COPY.medical,
  },
  {
    id: 'wikivoyage-en-nopic',
    title: 'Wikivoyage English',
    description:
      'Offline travel and geography reference for countries, cities, routes, and transport.',
    category: 'Wiki',
    format: 'zim',
    estimatedSize: '221 MB',
    sizeBytes: 221 * 1024 * 1024,
    sourceUrl: 'https://download.kiwix.org/zim/wikivoyage/wikivoyage_en_all_nopic_2026-03.zim',
    checksumSha256Url: kiwixSha256Url(
      'https://download.kiwix.org/zim/wikivoyage/wikivoyage_en_all_nopic_2026-03.zim'
    ),
    sourceLabel: 'Kiwix ZIM archive',
    fileName: 'wikivoyage_en_all_nopic_2026-03.zim',
    installed: false,
  },
  {
    id: 'wikipedia-en-top100-nopic',
    title: 'Wikipedia Top 100',
    description: 'Tiny smoke-test archive with the top English Wikipedia pages, no images.',
    category: 'Wiki',
    format: 'zim',
    estimatedSize: '13 MB',
    sizeBytes: 13 * 1024 * 1024,
    sourceUrl: 'https://download.kiwix.org/zim/wikipedia/wikipedia_en_100_nopic_2026-04.zim',
    checksumSha256Url: kiwixSha256Url(
      'https://download.kiwix.org/zim/wikipedia/wikipedia_en_100_nopic_2026-04.zim'
    ),
    sourceLabel: 'Kiwix ZIM archive',
    fileName: 'wikipedia_en_100_nopic_2026-04.zim',
    installed: false,
  },
  {
    id: 'embedding-nomic-v15-q4-k-m',
    title: 'Nomic Embed Text v1.5 Q4_K_M',
    description:
      'Compact search model for finding relevant offline notes, documents, guides, and wiki articles.',
    category: 'AI Models',
    format: 'gguf',
    modelRole: 'embedding',
    estimatedSize: '84 MB',
    sizeBytes: Math.round(84.1 * 1024 * 1024),
    sourceUrl:
      'https://huggingface.co/nomic-ai/nomic-embed-text-v1.5-GGUF/resolve/main/nomic-embed-text-v1.5.Q4_K_M.gguf',
    sourceLabel: 'Hugging Face: Nomic AI',
    fileName: 'nomic-embed-text-v1.5.Q4_K_M.gguf',
    installed: false,
    disclaimer: SAFETY_COPY.ai,
  },
  {
    id: 'embedding-qwen3-06b-q8',
    title: 'Qwen3 Embedding 0.6B Q8_0',
    description:
      'Optional multilingual embedding model for higher-quality retrieval across Portuguese and English.',
    category: 'AI Models',
    format: 'gguf',
    modelRole: 'embedding',
    estimatedSize: '639 MB',
    sizeBytes: 639 * 1024 * 1024,
    sourceUrl:
      'https://huggingface.co/Qwen/Qwen3-Embedding-0.6B-GGUF/resolve/main/Qwen3-Embedding-0.6B-Q8_0.gguf',
    sourceLabel: 'Hugging Face: Qwen',
    fileName: 'Qwen3-Embedding-0.6B-Q8_0.gguf',
    installed: false,
    disclaimer: SAFETY_COPY.ai,
  },
  {
    id: 'model-qwen25-15b-q4-0',
    title: 'Qwen2.5 1.5B Instruct Q4_0',
    description: 'Small Apache-2.0 GGUF model for local chat in builds with on-device AI enabled.',
    category: 'AI Models',
    format: 'gguf',
    modelRole: 'chat',
    estimatedSize: '1.07 GB',
    sizeBytes: Math.round(1.07 * 1024 * 1024 * 1024),
    sourceUrl:
      'https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF/resolve/main/qwen2.5-1.5b-instruct-q4_0.gguf',
    sourceLabel: 'Hugging Face: Qwen',
    fileName: 'qwen2.5-1.5b-instruct-q4_0.gguf',
    checksumSha256: 'dcd819ff094852c38faba6873d8ff0c9d51eadb2844539e52042ae5d647bbfdb',
    installed: false,
    disclaimer: SAFETY_COPY.ai,
  },
  {
    id: 'model-smollm2-17b-q4-0',
    title: 'SmolLM2 1.7B Instruct Q4_0',
    description:
      'Compact Apache-2.0 GGUF instruction model for phones with enough storage and memory.',
    category: 'AI Models',
    format: 'gguf',
    modelRole: 'chat',
    estimatedSize: '991 MB',
    sizeBytes: 991 * 1024 * 1024,
    sourceUrl:
      'https://huggingface.co/QuantFactory/SmolLM2-1.7B-Instruct-GGUF/resolve/main/SmolLM2-1.7B-Instruct.Q4_0.gguf',
    sourceLabel: 'Hugging Face: QuantFactory',
    fileName: 'SmolLM2-1.7B-Instruct.Q4_0.gguf',
    checksumSha256: '0b1491225b73a81885bfc190d1416e366d6698195285fbd4458caffaac99820e',
    installed: false,
    disclaimer: SAFETY_COPY.ai,
  },
  // ---- Official disaster & safety web guides ----
  {
    id: 'disaster-power-outage',
    title: 'Power Outage',
    description: 'What to do during blackouts, grid failure, and long outages.',
    category: 'Disasters',
    format: 'html',
    downloadStrategy: 'html_snapshot',
    estimatedSize: 'Web page',
    sourceUrl: 'https://www.ready.gov/power-outages/',
    sourceLabel: 'Ready.gov',
    fileName: 'ready-power-outage.html',
    installed: false,
    disclaimer: SAFETY_COPY.disaster,
  },
  {
    id: 'disaster-floods',
    title: 'Floods',
    description: 'Flood safety before, during, and after an event.',
    category: 'Disasters',
    format: 'html',
    downloadStrategy: 'html_snapshot',
    estimatedSize: 'Web page',
    sourceUrl: 'https://www.ready.gov/floods',
    sourceLabel: 'Ready.gov',
    fileName: 'ready-floods.html',
    installed: false,
    disclaimer: SAFETY_COPY.disaster,
  },
  {
    id: 'disaster-earthquakes',
    title: 'Earthquakes',
    description: 'Drop, cover, hold on, and prepare for aftershocks.',
    category: 'Disasters',
    format: 'html',
    downloadStrategy: 'html_snapshot',
    estimatedSize: 'Web page',
    sourceUrl: 'https://www.ready.gov/earthquakes',
    sourceLabel: 'Ready.gov',
    fileName: 'ready-earthquakes.html',
    installed: false,
    disclaimer: SAFETY_COPY.disaster,
  },
  {
    id: 'disaster-wildfires',
    title: 'Wildfires',
    description: 'Evacuation, air quality, and protecting your home from wildfire.',
    category: 'Disasters',
    format: 'html',
    downloadStrategy: 'html_snapshot',
    estimatedSize: 'Web page',
    sourceUrl: 'https://www.ready.gov/wildfires',
    sourceLabel: 'Ready.gov',
    fileName: 'ready-wildfires.html',
    installed: false,
    disclaimer: SAFETY_COPY.disaster,
  },
  {
    id: 'disaster-extreme-heat',
    title: 'Extreme Heat',
    description: 'Heat safety, hydration, and recognizing heat-related illness.',
    category: 'Disasters',
    format: 'html',
    downloadStrategy: 'html_snapshot',
    estimatedSize: 'Web page',
    sourceUrl: 'https://www.ready.gov/heat',
    sourceLabel: 'Ready.gov',
    fileName: 'ready-extreme-heat.html',
    installed: false,
    disclaimer: SAFETY_COPY.disaster,
  },
  {
    id: 'food-preservation-usda',
    title: 'USDA Guide to Home Canning',
    description: 'Official safe food preservation principles and practices.',
    category: 'Preparedness',
    format: 'html',
    downloadStrategy: 'html_snapshot',
    estimatedSize: 'Web page',
    sourceUrl: 'https://nchfp.uga.edu/resources/category/usda-guide',
    sourceLabel: 'NCHFP / USDA',
    fileName: 'usda-home-canning.html',
    installed: false,
    disclaimer: SAFETY_COPY.food,
  },
  {
    id: 'sanitation-hygiene',
    title: 'Sanitation & Hygiene After Disasters',
    description: 'Clean water, waste handling, and disease prevention after disasters.',
    category: 'Preparedness',
    format: 'html',
    downloadStrategy: 'html_snapshot',
    estimatedSize: 'Web page',
    sourceUrl:
      'https://www.cdc.gov/water-emergency/safety/guidelines-for-personal-hygiene-during-an-emergency.html',
    sourceLabel: 'CDC',
    fileName: 'cdc-sanitation-hygiene.html',
    installed: false,
    disclaimer: SAFETY_COPY.medical,
  },
];
