import { SAFETY_COPY } from '@/constants/app';
import type { ContentPackManifest } from '@/types/content';

export const STARTER_PACKS: ContentPackManifest[] = [
  {
    id: 'hesperian-first-aid',
    title: 'Hesperian First Aid',
    description: 'Field-focused emergency care chapter from New Where There Is No Doctor.',
    category: 'Medical',
    format: 'pdf',
    estimatedSize: 'PDF chapter',
    sourceUrl: 'https://hesperian.org/wp-content/uploads/pdf/en_nwtnd_2011/en_nwtnd_2014_03g.pdf',
    sourceLabel: 'Hesperian Health Guides',
    fileName: 'hesperian-first-aid.pdf',
    installed: false,
    disclaimer: SAFETY_COPY.medical,
  },
  {
    id: 'us-army-survival-fm-21-76',
    title: 'US Army Survival Manual',
    description:
      'FM 21-76 survival reference covering shelter, water, fire, navigation, and signaling.',
    category: 'Survival',
    format: 'pdf',
    estimatedSize: '2.9 MB',
    sourceUrl:
      'https://ia601604.us.archive.org/28/items/Fm21-76SurvivalManual/FM21-76_SurvivalManual.pdf',
    sourceLabel: 'Internet Archive',
    fileName: 'fm-21-76-survival-manual.pdf',
    installed: false,
  },
  {
    id: 'where-there-is-no-doctor-first-aid',
    title: 'Where There Is No Doctor: First Aid',
    description: 'Classic Hesperian first-aid chapter for low-resource primary care situations.',
    category: 'Medical',
    format: 'pdf',
    estimatedSize: 'PDF chapter',
    sourceUrl: 'https://hesperian.org/wp-content/uploads/pdf/en_wtnd_2025/en_wtnd_2025_10.pdf',
    sourceLabel: 'Hesperian Health Guides',
    fileName: 'where-there-is-no-doctor-first-aid.pdf',
    installed: false,
    disclaimer: SAFETY_COPY.medical,
  },
  {
    id: 'wikipedia-simple-en-nopic',
    title: 'Simple English Wikipedia',
    description:
      'Complete Simple English Wikipedia, no images. Best first Wikipedia archive for phones.',
    category: 'Wiki',
    format: 'zim',
    estimatedSize: '937 MB',
    sizeBytes: 937 * 1024 * 1024,
    sourceUrl: 'https://download.kiwix.org/zim/wikipedia/wikipedia_en_simple_all_nopic_2026-05.zim',
    sourceLabel: 'Kiwix ZIM archive',
    fileName: 'wikipedia_en_simple_all_nopic_2026-05.zim',
    installed: false,
  },
  {
    id: 'wikipedia-simple-en-mini',
    title: 'Simple English Wikipedia Mini',
    description: 'Introductory article extracts only. Smaller archive for low-storage devices.',
    category: 'Wiki',
    format: 'zim',
    estimatedSize: '447 MB',
    sizeBytes: 447 * 1024 * 1024,
    sourceUrl: 'https://download.kiwix.org/zim/wikipedia/wikipedia_en_simple_all_mini_2026-05.zim',
    sourceLabel: 'Kiwix ZIM archive',
    fileName: 'wikipedia_en_simple_all_mini_2026-05.zim',
    installed: false,
  },
  {
    id: 'medical-wikipedia-en-nopic',
    title: 'Medical Wikipedia',
    description:
      'English medical Wikipedia collection without images for offline health reference.',
    category: 'Medical',
    format: 'zim',
    estimatedSize: '822 MB',
    sizeBytes: 822 * 1024 * 1024,
    sourceUrl: 'https://download.kiwix.org/zim/wikipedia/wikipedia_en_medicine_nopic_2026-04.zim',
    sourceLabel: 'Kiwix ZIM archive',
    fileName: 'wikipedia_en_medicine_nopic_2026-04.zim',
    installed: false,
    disclaimer: SAFETY_COPY.medical,
  },
  {
    id: 'wikivoyage-en-nopic',
    title: 'Wikivoyage English',
    description:
      'Offline travel and geography reference for countries, cities, routes, and transport.',
    category: 'Wiki',
    format: 'zim',
    estimatedSize: '221 MB',
    sizeBytes: 221 * 1024 * 1024,
    sourceUrl: 'https://download.kiwix.org/zim/wikivoyage/wikivoyage_en_all_nopic_2026-03.zim',
    sourceLabel: 'Kiwix ZIM archive',
    fileName: 'wikivoyage_en_all_nopic_2026-03.zim',
    installed: false,
  },
  {
    id: 'wikipedia-en-top100-nopic',
    title: 'Wikipedia Top 100',
    description: 'Tiny smoke-test archive with the top English Wikipedia pages, no images.',
    category: 'Wiki',
    format: 'zim',
    estimatedSize: '13 MB',
    sizeBytes: 13 * 1024 * 1024,
    sourceUrl: 'https://download.kiwix.org/zim/wikipedia/wikipedia_en_100_nopic_2026-04.zim',
    sourceLabel: 'Kiwix ZIM archive',
    fileName: 'wikipedia_en_100_nopic_2026-04.zim',
    installed: false,
  },
  {
    id: 'model-qwen25-15b-q4-0',
    title: 'Qwen2.5 1.5B Instruct Q4_0',
    description:
      'Small Apache-2.0 GGUF model for local chat once llama.rn is available in a dev build.',
    category: 'AI Models',
    format: 'gguf',
    estimatedSize: '1.07 GB',
    sizeBytes: Math.round(1.07 * 1024 * 1024 * 1024),
    sourceUrl:
      'https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF/resolve/main/qwen2.5-1.5b-instruct-q4_0.gguf',
    sourceLabel: 'Hugging Face: Qwen',
    fileName: 'qwen2.5-1.5b-instruct-q4_0.gguf',
    installed: false,
    disclaimer: SAFETY_COPY.ai,
  },
  {
    id: 'model-smollm2-17b-q4-0',
    title: 'SmolLM2 1.7B Instruct Q4_0',
    description:
      'Compact Apache-2.0 GGUF instruction model for phones with enough storage and memory.',
    category: 'AI Models',
    format: 'gguf',
    estimatedSize: '991 MB',
    sizeBytes: 991 * 1024 * 1024,
    sourceUrl:
      'https://huggingface.co/QuantFactory/SmolLM2-1.7B-Instruct-GGUF/resolve/main/SmolLM2-1.7B-Instruct.Q4_0.gguf',
    sourceLabel: 'Hugging Face: QuantFactory',
    fileName: 'SmolLM2-1.7B-Instruct.Q4_0.gguf',
    installed: false,
    disclaimer: SAFETY_COPY.ai,
  },
];
